config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'pages#home', as: 'home'

  get 'about_us', to: 'pages#about', as: 'about'
  
  get 'lizards/:number', to: 'pages#lizards', as: 'lizards'
  
  get 'cats', to: 'cats#index', as: 'cats'
  
  get 'cats/:id', to: 'cats#show', as: 'cat'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  validates :name, :breed, :registry, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.order(:name)
  end
  
  def show
    @cat = Cat.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
  
  def lizards
    @lizard_num = params[:number].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cats/_cats.html.erb
<h1>Cat</h1>
<% cat = @cat %>
<h2><%= cat.name %></h2>
<p><%= cat.breed %></p>
<p><%= cat.registry %><p>

app/views/cats/index.html.erb
<h1>Cats</h1>

<% @cats.each do |cat| %>
  <h2><%= cat.name %></h2>
  <p><%= cat.breed %></p>
  <p><%= cat.registry %><p>  
<% end %>

app/views/cats/show.html.erb
<h1>Cat</h1>
<% cat = @cat %>
<h2><%= cat.name %></h2>
<p><%= cat.breed %></p>
<p><%= cat.registry %><p>

app/views/common/_menu.html.erb
<ul>
  <li><%= link_to 'Home', home_path %></li>
  <li><%= link_to 'About Us', about_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge4dot5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body {
        background-color: #00FF00;
      }
    </style
  </head>

  <body>
  <%= render "common/menu" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<h2>Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</h2>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Home</h1>
<h2>Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</h2>
<ul>
  <li><%= link_to '12 Lizards', lizards_path(12) %></li>
  <li><%= link_to '1444 Lizards', lizards_path(444) %></li>
  <li><%= link_to '9672 Lizards', lizards_path(9672) %></li>
</ul>

app/views/pages/lizards.html.erb
<h1>Lizards!</h1>
<% @lizard_num.times do %>
  <p>🦎</p>
<% end %>